export const CATEGORIES = [
  { id: "roots", ru: "Блок 1. Корни и семья", en: "Block 1. Roots & Family", emoji: "🌳" },
  { id: "personality", ru: "Блок 2. Личность и ценности", en: "Block 2. Personality & Values", emoji: "🧭" },
  { id: "love", ru: "Блок 3. Отношения и любовь", en: "Block 3. Relationships & Love", emoji: "💗" },
  { id: "future", ru: "Блок 4. Жизнь и будущее", en: "Block 4. Life & Future", emoji: "🔭" },
  { id: "spiritual", ru: "Блок 5. Духовное и глубинное", en: "Block 5. Spirituality & Depth", emoji: "✨" },
  { id: "us", ru: "Блок 6. Про «нас»", en: "Block 6. About \"Us\"", emoji: "💑" },
  { id: "finance", ru: "Блок 7. Финансы и материальная сторона отношений", en: "Block 7. Finances & the Material Side of the Relationship", emoji: "💰" },
  { id: "kids", ru: "Блок 8. Дети и родительство", en: "Block 8. Children & Parenthood", emoji: "👶" },
  { id: "conflict", ru: "Блок 9. Конфликты и разногласия", en: "Block 9. Conflicts & Disagreements", emoji: "⚡" },
  { id: "stress", ru: "Блок 10. Стресс, кризисы", en: "Block 10. Stress & Crises", emoji: "🌪️" },
  { id: "freedom", ru: "Блок 11. Свобода, границы и безопасность", en: "Block 11. Freedom, Boundaries & Safety", emoji: "🕊️" },
];

export const QUESTIONS = [
  // Блок 1. Корни и семья
  { id: 1, cat: "roots", ru: "Какие классная и не очень классная черты твоего характера пришли от мамы/папы?", en: "Which of your character traits — both great and not so great — came from your mom or dad?" },
  { id: 2, cat: "roots", ru: "Какая традиция твоей семьи тебе дорога?", en: "What family tradition is dear to you?" },
  { id: 3, cat: "roots", ru: "Что бы ты хотел передать детям (если они будут) из своего рода?", en: "What would you want to pass on to your children (if you have them) from your family line?" },
  { id: 4, cat: "roots", ru: "Чему тебя научили трудные отношения в семье?", en: "What did difficult relationships in your family teach you?" },
  { id: 5, cat: "roots", ru: "Что для тебя значит «дом»?", en: "What does \"home\" mean to you?" },
  { id: 6, cat: "roots", ru: "Как ты любишь встречать/провожать близких?", en: "How do you like to welcome or see off loved ones?" },
  { id: 7, cat: "roots", ru: "Что для тебя «безопасное пространство»?", en: "What is a \"safe space\" for you?" },
  { id: 8, cat: "roots", ru: "В чем твоя семья тебя недопоняла?", en: "In what way did your family fail to understand you?" },
  { id: 9, cat: "roots", ru: "В чем они тебя очень поддержали?", en: "In what way did they support you the most?" },
  { id: 10, cat: "roots", ru: "Какая память из детства согревает тебя больше всего?", en: "Which childhood memory warms you the most?" },

  // Блок 2. Личность и ценности
  { id: 11, cat: "personality", ru: "Какое качество ты в себе любишь?", en: "What quality do you love about yourself?" },
  { id: 12, cat: "personality", ru: "Какое качество в себе еще принимаешь с трудом?", en: "What quality about yourself is still hard to accept?" },
  { id: 13, cat: "personality", ru: "Где твоя сила?", en: "Where does your strength lie?" },
  { id: 14, cat: "personality", ru: "Где твоя уязвимость?", en: "Where is your vulnerability?" },
  { id: 15, cat: "personality", ru: "Что делает тебя свободным?", en: "What makes you feel free?" },
  { id: 16, cat: "personality", ru: "Что делает тебя привязанным?", en: "What makes you feel attached?" },
  { id: 17, cat: "personality", ru: "Какая ценность для тебя абсолютна?", en: "What value is absolute for you?" },
  { id: 18, cat: "personality", ru: "Что такое для тебя честность в отношениях?", en: "What does honesty in a relationship mean to you?" },
  { id: 19, cat: "personality", ru: "Какая форма заботы для тебя самая ценная?", en: "What form of care matters most to you?" },
  { id: 20, cat: "personality", ru: "В чем для тебя «успех»?", en: "What does \"success\" mean to you?" },

  // Блок 3. Отношения и любовь
  { id: 21, cat: "love", ru: "Как ты понимаешь слово «верность»?", en: "How do you understand the word \"faithfulness\"?" },
  { id: 22, cat: "love", ru: "Чему тебя научил самый трудный разрыв?", en: "What did your hardest breakup teach you?" },
  { id: 23, cat: "love", ru: "Что для тебя «идеальный партнер»?", en: "What is an \"ideal partner\" for you?" },
  { id: 24, cat: "love", ru: "Какое проявление любви тебя трогает больше всего?", en: "What expression of love touches you the most?" },
  { id: 25, cat: "love", ru: "Что для тебя значит «быть настоящим рядом»?", en: "What does it mean to you to \"be truly present\" with someone?" },
  { id: 26, cat: "love", ru: "Какая мелочь в паре для тебя важнее, чем кажется?", en: "What small thing in a couple matters more to you than it seems?" },
  { id: 27, cat: "love", ru: "Как ты любишь мириться?", en: "How do you like to make up after a fight?" },
  { id: 28, cat: "love", ru: "В чем для тебя «сакральность секса»?", en: "What does the \"sacredness of sex\" mean to you?" },
  { id: 29, cat: "love", ru: "Как ты хочешь чувствовать себя рядом с партнером?", en: "How do you want to feel next to your partner?" },
  { id: 30, cat: "love", ru: "В чем твоя потребность в свободе в отношениях?", en: "What is your need for freedom within a relationship?" },

  // Блок 4. Жизнь и будущее
  { id: 31, cat: "future", ru: "Где ты видишь себя через 5 лет?", en: "Where do you see yourself in 5 years?" },
  { id: 32, cat: "future", ru: "Как ты представляешь идеальный день, проведённый вдвоём?", en: "What does an ideal day spent together look like to you?" },
  { id: 33, cat: "future", ru: "Если бы у тебя был год свободы, что бы ты сделал?", en: "If you had a free year, what would you do?" },
  { id: 34, cat: "future", ru: "Какой проект в жизни для тебя главный?", en: "What is the main project of your life?" },
  { id: 35, cat: "future", ru: "Что для тебя «миссия»?", en: "What does \"mission\" mean to you?" },
  { id: 36, cat: "future", ru: "Если бы ты выиграл большую сумму денег, на что бы потратил?", en: "If you won a large sum of money, what would you spend it on?" },
  { id: 37, cat: "future", ru: "Что для тебя «богатство»?", en: "What does \"wealth\" mean to you?" },
  { id: 38, cat: "future", ru: "Если бы у нас был совместный проект, что бы это было?", en: "If we had a joint project together, what would it be?" },
  { id: 39, cat: "future", ru: "Где ты хотел бы путешествовать вместе?", en: "Where would you like to travel together?" },
  { id: 40, cat: "future", ru: "Какая жизнь для тебя «правильная»?", en: "What kind of life feels \"right\" to you?" },

  // Блок 5. Духовное и глубинное
  { id: 41, cat: "spiritual", ru: "Что для тебя Бог/Дух/Вселенная?", en: "What does God/Spirit/the Universe mean to you?" },
  { id: 42, cat: "spiritual", ru: "Есть ли у тебя ритуал, который поддерживает?", en: "Do you have a ritual that supports you?" },
  { id: 43, cat: "spiritual", ru: "Когда ты последний раз чувствовал(а) абсолютное счастье?", en: "When did you last feel absolute happiness?" },
  { id: 44, cat: "spiritual", ru: "Когда ты последний раз чувствовал боль, которая изменила тебя? Что это было?", en: "When did you last feel pain that changed you? What was it?" },
  { id: 45, cat: "spiritual", ru: "Как ты хочешь расти как мужчина (как женщина)?", en: "How do you want to grow as a man (as a woman)?" },
  { id: 46, cat: "spiritual", ru: "Что для тебя «принятие»?", en: "What does \"acceptance\" mean to you?" },
  { id: 47, cat: "spiritual", ru: "Как ты относишься к прощению?", en: "How do you feel about forgiveness?" },
  { id: 48, cat: "spiritual", ru: "В чем твое предназначение?", en: "What is your purpose?" },
  { id: 49, cat: "spiritual", ru: "Что для тебя смерть?", en: "What does death mean to you?" },
  { id: 50, cat: "spiritual", ru: "Что для тебя вечность?", en: "What does eternity mean to you?" },

  // Блок 6. Про «нас»
  { id: 51, cat: "us", ru: "Что ты боишься потерять рядом со мной?", en: "What are you afraid of losing by being with me?" },
  { id: 52, cat: "us", ru: "Что хочешь обрести со мной?", en: "What do you want to gain with me?" },
  { id: 53, cat: "us", ru: "Какая наша разница тебе нравится?", en: "Which of our differences do you like?" },
  { id: 54, cat: "us", ru: "Что тебя больше всего тянет ко мне?", en: "What draws you to me the most?" },
  { id: 55, cat: "us", ru: "В чем ты хочешь, чтобы я была (был) свободной?", en: "In what way do you want me to be free?" },
  { id: 56, cat: "us", ru: "Что ты хочешь, чтобы мы никогда не теряли?", en: "What do you want us to never lose?" },
  { id: 57, cat: "us", ru: "Каким ты видишь наше будущее через несколько лет?", en: "How do you see our future in a few years?" },
  { id: 58, cat: "us", ru: "Напиши, как с тобой недопустимо себя вести / чего ты не примешь?", en: "Write down how it's unacceptable to treat you / what you won't accept." },
  { id: 59, cat: "us", ru: "Что ты хочешь, чтобы я чувствовала (чувствовал) рядом с тобой?", en: "What do you want me to feel next to you?" },
  { id: 60, cat: "us", ru: "Что для тебя стало бы нашей главной опорой в трудный момент?", en: "What would be our main support in a difficult moment for you?" },

  // Блок 7. Финансы и материальная сторона отношений
  { id: 61, cat: "finance", ru: "Как ты представляешь финансовую модель пары: общий бюджет, раздельный или смешанный?", en: "How do you imagine the couple's financial model: shared budget, separate, or mixed?" },
  { id: 62, cat: "finance", ru: "Как, по-твоему, должны распределяться общие расходы?", en: "How do you think shared expenses should be split?" },
  { id: 63, cat: "finance", ru: "Как ты относишься к ситуации, когда один партнёр зарабатывает значительно больше другого?", en: "How do you feel about a situation where one partner earns significantly more than the other?" },
  { id: 64, cat: "finance", ru: "Есть ли у тебя долги, кредиты или другие финансовые обязательства, о которых мне важно знать?", en: "Do you have any debts, loans, or other financial obligations I should know about?" },
  { id: 65, cat: "finance", ru: "Как ты относишься к финансовой помощи родителям, родственникам или друзьям?", en: "How do you feel about giving financial help to parents, relatives, or friends?" },
  { id: 66, cat: "finance", ru: "Какую сумму или какие траты партнёры должны обсуждать друг с другом заранее?", en: "What amount or which expenses should partners discuss with each other in advance?" },
  { id: 67, cat: "finance", ru: "Что для тебя считается личными деньгами, а что — общими?", en: "What counts as personal money for you, and what counts as shared?" },
  { id: 68, cat: "finance", ru: "Как ты относишься к крупным покупкам без согласования с партнёром?", en: "How do you feel about making large purchases without consulting your partner?" },
  { id: 69, cat: "finance", ru: "Что для тебя будет финансовым предательством в отношениях?", en: "What would count as financial betrayal in a relationship for you?" },
  { id: 70, cat: "finance", ru: "Как ты представляешь финансовую безопасность семьи: накопления, подушка, инвестиции, имущество?", en: "How do you envision the family's financial security: savings, a safety cushion, investments, property?" },
  { id: 71, cat: "finance", ru: "Что происходит с финансами пары, если один из партнёров временно не может работать?", en: "What happens to the couple's finances if one partner is temporarily unable to work?" },
  { id: 72, cat: "finance", ru: "Как ты относишься к тому, чтобы иметь отдельные накопления, о которых партнёр знает, но которыми не распоряжается?", en: "How do you feel about having separate savings that your partner knows about but doesn't control?" },

  // Блок 8. Дети и родительство
  { id: 73, cat: "kids", ru: "Хочешь ли ты детей? Если да — сколько и когда примерно?", en: "Do you want children? If so, how many and roughly when?" },
  { id: 74, cat: "kids", ru: "Что ты хочешь получить от родительства как человек?", en: "What do you want to gain from parenthood as a person?" },
  { id: 75, cat: "kids", ru: "Что в родительстве тебя больше всего привлекает, а что пугает?", en: "What attracts you most about parenthood, and what scares you?" },
  { id: 76, cat: "kids", ru: "Каким родителем ты хочешь быть?", en: "What kind of parent do you want to be?" },
  { id: 77, cat: "kids", ru: "Какие качества ты хотел передать своим детям?", en: "What qualities would you want to pass on to your children?" },
  { id: 78, cat: "kids", ru: "Что из своего детства ты обязательно хочешь повторить со своими детьми?", en: "What from your own childhood do you definitely want to repeat with your children?" },
  { id: 79, cat: "kids", ru: "Что из своего детства ты категорически не хочешь повторять?", en: "What from your own childhood do you absolutely not want to repeat?" },
  { id: 80, cat: "kids", ru: "Как ты представляешь себе распределение обязанностей после рождения ребёнка?", en: "How do you imagine dividing responsibilities after a child is born?" },
  { id: 81, cat: "kids", ru: "Кто и сколько, по-твоему, должен заниматься ребёнком в первые годы жизни?", en: "Who, and how much, do you think should care for the child in the first years of life?" },
  { id: 82, cat: "kids", ru: "Как мы будем находить время друг для друга, если станем родителями?", en: "How will we find time for each other if we become parents?" },
  { id: 83, cat: "kids", ru: "Как мы будем сохранять интимную и эмоциональную близость после рождения ребёнка?", en: "How will we maintain intimate and emotional closeness after the child is born?" },
  { id: 84, cat: "kids", ru: "Как ты представляешь себе дисциплину и наказания?", en: "How do you envision discipline and punishment?" },
  { id: 85, cat: "kids", ru: "Что для тебя допустимо в воспитании, а что категорически недопустимо?", en: "What is acceptable to you in parenting, and what is absolutely not?" },
  { id: 86, cat: "kids", ru: "Как мы будем принимать решения, если наши взгляды на воспитание будут различаться?", en: "How will we make decisions if our views on parenting differ?" },
  { id: 87, cat: "kids", ru: "Как ты относишься к помощи бабушек, родственников, няни?", en: "How do you feel about help from grandparents, relatives, or a nanny?" },
  { id: 88, cat: "kids", ru: "Что будет происходить с отношениями пары, если ребёнок станет главным фокусом одного из партнёров?", en: "What will happen to the couple's relationship if the child becomes the main focus of one partner?" },
  { id: 89, cat: "kids", ru: "Как ты представляешь себе участие отца и матери в жизни ребёнка?", en: "How do you envision the father's and mother's involvement in the child's life?" },
  { id: 90, cat: "kids", ru: "Что для тебя важнее в воспитании: послушание, самостоятельность, эмоциональный контакт, дисциплина, достижения?", en: "What matters more to you in parenting: obedience, independence, emotional connection, discipline, or achievement?" },

  // Блок 9. Конфликты и разногласия
  { id: 91, cat: "conflict", ru: "Что происходит с тобой в конфликте?", en: "What happens to you during a conflict?" },
  { id: 92, cat: "conflict", ru: "Что ты делаешь, когда понимаешь, что партнёр не согласен с твоей точкой зрения?", en: "What do you do when you realize your partner disagrees with your point of view?" },
  { id: 93, cat: "conflict", ru: "Что с тобой происходит, когда ты злишься?", en: "What happens to you when you get angry?" },
  { id: 94, cat: "conflict", ru: "Можно ли брать паузу во время конфликта? Как именно сообщать об этом партнёру?", en: "Is it okay to take a pause during a conflict? How exactly should that be communicated to your partner?" },
  { id: 95, cat: "conflict", ru: "Сколько времени тебе обычно нужно, чтобы вернуться к спокойному разговору?", en: "How much time do you usually need to return to a calm conversation?" },
  { id: 96, cat: "conflict", ru: "Что помогает тебе успокоиться после конфликта?", en: "What helps you calm down after a conflict?" },
  { id: 97, cat: "conflict", ru: "Как ты обычно просишь прощения?", en: "How do you usually apologize?" },
  { id: 98, cat: "conflict", ru: "Что для тебя недопустимо даже во время сильной злости?", en: "What is unacceptable to you even during intense anger?" },
  { id: 99, cat: "conflict", ru: "Какие слова или действия партнёра могут разрушить твоё чувство безопасности?", en: "What words or actions from your partner could destroy your sense of safety?" },
  { id: 100, cat: "conflict", ru: "Как ты хочешь, чтобы партнёр говорил с тобой о проблемах, которые тебе неприятно слышать?", en: "How do you want your partner to talk to you about issues that are unpleasant for you to hear?" },

  // Блок 10. Стресс, кризисы
  { id: 101, cat: "stress", ru: "Что с тобой происходит, когда ты очень устал?", en: "What happens to you when you're very tired?" },
  { id: 102, cat: "stress", ru: "Как понять, что тебе плохо, даже если ты об этом не говоришь?", en: "How can one tell you're not okay, even if you don't say it?" },
  { id: 103, cat: "stress", ru: "Что партнёр может сделать для тебя в состоянии сильного стресса?", en: "What can your partner do for you when you're under a lot of stress?" },
  { id: 104, cat: "stress", ru: "Что, наоборот, партнёру лучше не делать, когда тебе плохо?", en: "What, on the contrary, is better for your partner not to do when you're feeling bad?" },
  { id: 105, cat: "stress", ru: "Как ты реагируешь, когда чувствуешь, что теряешь контроль над ситуацией?", en: "How do you react when you feel you're losing control of a situation?" },
  { id: 106, cat: "stress", ru: "Что происходит с тобой во время сильного эмоционального напряжения?", en: "What happens to you during intense emotional strain?" },
  { id: 107, cat: "stress", ru: "Как ты обычно справляешься с кризисами?", en: "How do you usually cope with crises?" },
  { id: 108, cat: "stress", ru: "Как ты просишь о помощи, когда сам не справляешься?", en: "How do you ask for help when you can't cope on your own?" },
  { id: 109, cat: "stress", ru: "Что тебе нужно от партнёра в сложный период: присутствие, объятия, разговор, пространство, практическая помощь?", en: "What do you need from your partner during a hard time: presence, hugs, conversation, space, or practical help?" },

  // Блок 11. Свобода, границы и безопасность
  { id: 110, cat: "freedom", ru: "Что для тебя означает свобода внутри отношений?", en: "What does freedom within a relationship mean to you?" },
  { id: 111, cat: "freedom", ru: "Сколько личного пространства тебе необходимо?", en: "How much personal space do you need?" },
  { id: 112, cat: "freedom", ru: "Что будет, если одному из нас понадобится больше свободы?", en: "What happens if one of us needs more freedom?" },
  { id: 113, cat: "freedom", ru: "Как ты относишься к отдельному времени, поездкам или отдыху без партнёра?", en: "How do you feel about separate time, trips, or vacations without your partner?" },
  { id: 114, cat: "freedom", ru: "Какие границы для тебя принципиальны?", en: "Which boundaries are non-negotiable for you?" },
  { id: 115, cat: "freedom", ru: "Что ты считаешь нарушением личных границ?", en: "What do you consider a violation of personal boundaries?" },
  { id: 116, cat: "freedom", ru: "Что помогает тебе чувствовать себя любимым и в безопасности в отношениях?", en: "What helps you feel loved and safe in a relationship?" },
  { id: 117, cat: "freedom", ru: "Как ты ведёшь себя, когда боишься потерять отношения?", en: "How do you behave when you're afraid of losing the relationship?" },
  { id: 118, cat: "freedom", ru: "Что для тебя является изменой — только секс или также эмоциональная близость, флирт, переписки?", en: "What counts as cheating for you — only sex, or also emotional intimacy, flirting, messaging?" },
  { id: 119, cat: "freedom", ru: "Что ты считаешь достаточной открытостью между партнёрами, а что уже нарушением приватности?", en: "What do you consider sufficient openness between partners, and what already crosses into a privacy violation?" },
];
